spring:
  application:
    name: zuul-service
server:
  port: 8903
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
zuul:
  prefix: /api
  routes:
    hello-server:
      path: /server/**
      service-id: hello-server
    hello-client:
      path: /client/**
      service-id: hello-client
    db-service:
      path: /dbservice/**
      service-id: db-service
  